### ISSUE TITLE
No way to change font with inline styles

### ISSUE THREAD

**Issue by bmathews** [conorhastings/react-syntax-highlighter#19]
Browsers have the following default css:

```css
code {
  font-family: monospace;
}
```

That means that currently there's no way to change the font when using `react-syntax-highlighter` without a `<style>` element overriding that. If you add a `fontFamily` style to the `<pre>` element, it has no effect.

It seems like a good solution would be to add `fontFamily: inherit` to the `<code>` element, but that'd be a breaking change for some, probably.

**Comment by conorhastings** [comment]
This is interesting. The code tag is currently the only element you have no real access too. One option to prevent breaking change + undesirable potential effects is to have a prop for styling the code tag. 


Another option, which seems kind of terrible but possible would be to pass a className in to the syntax highlighter as a prop(this will be spread into the top level pre) and then target the code block from there

```css
.syntax-highlighter code {
  font-family: 'Comic Sans';
} 
```

let me know what you think?
