### ISSUE TITLE
How to prevent styles on `<pre/>`?

### ISSUE THREAD

**Issue by catamphetamine** [conorhastings/react-syntax-highlighter#199]
It seems to add the following styles on `<pre/>`:

```css
{
    display: block;
    overflow-x: auto;
    padding: 0.5em;
    color: rgb(0, 0, 0);
    background: rgb(248, 248, 255);
}
```

My workaround is:

```js
const language = 'javascript'
const codeString = '(num) => num + 1';
return (
	<SyntaxHighlighter
		customStyle={{
			display: undefined,
			overflowX: undefined,
			padding: undefined,
			color: undefined,
			background: undefined
		}}
		language={language}
		className={...}
		style={docco}
		codeTagProps={{ className: `language-${language}` }}>
		{codeString}
	</SyntaxHighlighter>
)
```

Is there a better way?
